<template>
  <div class="rea">person
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
    <div>shfdaskdjhfkashdk</div>
  </div>
</template>
<script>
export default {
  name: "person"
};
</script>
<style>
.rea {
  background-color: red;
}
</style>
